# Generated by Django 4.2.30 on 2026-04-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_alter_store_banner_alter_store_latitude_and_more'),
        ('retail_catalog', '0002_retailfavorite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='retailcategory',
            unique_together={('store', 'slug')},
        ),
        migrations.AddIndex(
            model_name='retailproduct',
            index=models.Index(fields=['store', 'is_active'], name='retail_prod_store_active_idx'),
        ),
    ]
