# Generated by Django 4.2.29 on 2026-03-23 10:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0003_store_store_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which category appears on the menu')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='stores.store')),
            ],
            options={
                'verbose_name_plural': 'Menu Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_menu/images/')),
                ('preparation_time_minutes', models.PositiveIntegerField(default=15, help_text='Estimated prep time')),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_spicy', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='food_menu.menucategory')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='stores.store')),
            ],
        ),
    ]
