# Generated by Django 4.2.30 on 2026-04-16 16:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('food_menu', '0002_foodfavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Size, Crust Type', max_length=100)),
                ('choices', models.JSONField(default=list, help_text="List of choice strings, e.g. ['Small', 'Medium', 'Large']")),
                ('is_required', models.BooleanField(default=False)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='food_menu.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemExtra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Extra Cheese, Avocado', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='food_menu.menuitem')),
            ],
        ),
    ]
