# Generated by Django 4.2.30 on 2026-04-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_menu', '0003_menuitemoption_menuitemextra'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['store', 'is_available'], name='menu_item_store_available_idx'),
        ),
    ]
