# Generated by Django 4.2.29 on 2026-03-15 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('BICYCLE', 'Bicycle'), ('MOTORCYCLE', 'Motorcycle'), ('CAR', 'Car'), ('VAN', 'Van')], default='MOTORCYCLE', max_length=20)),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('is_available', models.BooleanField(default=False)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_location_update', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('SEARCHING', 'Searching for Driver'), ('ASSIGNED', 'Driver Assigned'), ('ARRIVED_AT_STORE', 'Arrived at Store'), ('PICKED_UP', 'Picked Up'), ('ON_THE_WAY', 'On The Way'), ('DELIVERED', 'Delivered'), ('FAILED', 'Delivery Failed')], default='SEARCHING', max_length=20)),
                ('tracking_code', models.CharField(editable=False, max_length=12, unique=True)),
                ('delivery_photo', models.ImageField(blank=True, null=True, upload_to='deliveries/proof/')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='delivery.driver')),
            ],
        ),
    ]
