# Generated by Django 4.2.30 on 2026-04-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_savedpaymentmethod_customeraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='contact_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='address_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='title',
            field=models.CharField(blank=True, help_text='e.g., Home, Work', max_length=50, null=True),
        ),
    ]
