# Generated by Django 5.2.10 on 2026-01-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('food', 'Groceries'), ('home', 'Home & Garden'), ('art', 'Art & Crafts')], max_length=50),
        ),
    ]
