# Generated by Django 5.2.10 on 2026-02-01 13:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_store_payment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='payment_accounts',
            field=models.JSONField(blank=True, default=dict, help_text='Accounts/phones keyed by method name'),
        ),
        migrations.AlterField(
            model_name='store',
            name='payment_methods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('chapa', 'Chapa'), ('telebirr', 'Telebirr'), ('mpesa', 'M-Pesa')], max_length=20), blank=True, default=list, help_text='Enabled payment methods for this store', size=None),
        ),
    ]
