# Generated by Django 4.2.29 on 2026-03-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='announcement_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='store',
            name='announcement_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='announcement_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='background_color',
            field=models.CharField(default='#F9FAFB', max_length=7),
        ),
        migrations.AddField(
            model_name='store',
            name='body_font',
            field=models.CharField(default='Inter', max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='card_style',
            field=models.CharField(default='rounded-shadow', max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='header_layout',
            field=models.CharField(default='logo-left', max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='heading_font',
            field=models.CharField(default='Inter', max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='secondary_color',
            field=models.CharField(default='#111827', max_length=7),
        ),
        migrations.AddField(
            model_name='store',
            name='social_facebook',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='social_instagram',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='social_tiktok',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='social_twitter',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='primary_color',
            field=models.CharField(default='#4F46E5', max_length=7),
        ),
        migrations.AlterField(
            model_name='store',
            name='theme',
            field=models.CharField(default='modern', max_length=50),
        ),
    ]
