# Generated by Django 4.2.29 on 2026-03-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_announcement_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_type',
            field=models.CharField(choices=[('RETAIL', 'Retail Shop (Fashion, Tech, etc.)'), ('FOOD', 'Food & Coffee (Cafes, Restaurants)')], default='RETAIL', help_text='Determines which map gateway this store appears on.', max_length=20),
        ),
    ]
