# Generated by Django 4.2.30 on 2026-04-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_store_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='delivery_hours',
            field=models.CharField(blank=True, default='', help_text='e.g. 09:00 – 22:00', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='working_days',
            field=models.CharField(blank=True, default='', help_text='e.g. Monday – Saturday', max_length=100),
        ),
    ]
