# Generated by Django 4.2.30 on 2026-04-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_delivery_hours_store_working_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='subscription_plan',
            field=models.CharField(choices=[('STARTER', 'Starter (Free Trial)'), ('PRO', 'Pro'), ('ELITE', 'Elite')], default='STARTER', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='subscription_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('CANCELED', 'Canceled')], default='ACTIVE', max_length=20),
        ),
    ]
