# Generated by Antigravity
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_store_subscription_plan_store_subscription_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theme', models.CharField(default='modern', max_length=50)),
                ('primary_color', models.CharField(default='#4F46E5', max_length=7)),
                ('secondary_color', models.CharField(default='#111827', max_length=7)),
                ('background_color', models.CharField(default='#F9FAFB', max_length=7)),
                ('heading_font', models.CharField(default='Inter', max_length=50)),
                ('body_font', models.CharField(default='Inter', max_length=50)),
                ('header_layout', models.CharField(default='logo-left', max_length=50)),
                ('card_style', models.CharField(default='rounded-shadow', max_length=50)),
                ('working_days', models.CharField(blank=True, default='', help_text='e.g. Monday – Saturday', max_length=100)),
                ('delivery_hours', models.CharField(blank=True, default='', help_text='e.g. 09:00 – 22:00', max_length=100)),
                ('announcement_is_active', models.BooleanField(default=False)),
                ('announcement_text', models.CharField(blank=True, max_length=255)),
                ('announcement_color', models.CharField(default='#000000', max_length=7)),
                ('social_instagram', models.URLField(blank=True, max_length=255)),
                ('social_tiktok', models.URLField(blank=True, max_length=255)),
                ('social_facebook', models.URLField(blank=True, max_length=255)),
                ('social_twitter', models.URLField(blank=True, max_length=255)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_config', to='stores.store')),
            ],
        ),
        migrations.RemoveField(
            model_name='store',
            name='announcement_color',
        ),
        migrations.RemoveField(
            model_name='store',
            name='announcement_is_active',
        ),
        migrations.RemoveField(
            model_name='store',
            name='announcement_text',
        ),
        migrations.RemoveField(
            model_name='store',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='store',
            name='body_font',
        ),
        migrations.RemoveField(
            model_name='store',
            name='card_style',
        ),
        migrations.RemoveField(
            model_name='store',
            name='delivery_hours',
        ),
        migrations.RemoveField(
            model_name='store',
            name='header_layout',
        ),
        migrations.RemoveField(
            model_name='store',
            name='heading_font',
        ),
        migrations.RemoveField(
            model_name='store',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='store',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='store',
            name='social_facebook',
        ),
        migrations.RemoveField(
            model_name='store',
            name='social_instagram',
        ),
        migrations.RemoveField(
            model_name='store',
            name='social_tiktok',
        ),
        migrations.RemoveField(
            model_name='store',
            name='social_twitter',
        ),
        migrations.RemoveField(
            model_name='store',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='store',
            name='working_days',
        ),
    ]
