# Generated by Django 4.2.30 on 2026-04-19 07:29

import apps.stores.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_storetheme_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='stores/banners/', validators=[django.core.validators.validate_image_file_extension, apps.stores.models._validate_image_size]),
        ),
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='stores/logos/', validators=[django.core.validators.validate_image_file_extension, apps.stores.models._validate_image_size]),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
